export { default as IconMetamaskWallet } from './resource/metasmask.png'
export { default as IconCoinbaseWallet } from './resource/coinbasewallet.png'
export { default as IconWalletConnect } from './resource/walletconnect.png'
export { default as IconPhantomWallet } from './resource/phantomwallet.png'
export { default as IconTrustWallet } from './resource/trustwallet.png'
export { default as IconArgentWallet } from './resource/argentwallet.png'
export { default as IconLedgerLive } from './resource/ledgerlive.png'

export { default as IconETH } from './resource/eth.png'
export { default as IconBTC } from './resource/btc.png'
export { default as IconUSDT } from './resource/usdt.png'
export { default as IconPudgy } from './resource/pudgy.png'

export { default as IconMarPoint } from './resource/icon-mar-point.png'
export { default as IconMyStake } from './resource/icon-mystake.png'
export { default as IconPending } from './resource/icon-pending.png'
export { default as IconTotalValueStake } from './resource/icon-total-value-stake.png'
export { default as IconDailyReward } from './resource/icon-daily-reward.png'
export { default as IconYourDailyReward } from './resource/icon-your-daily-reward.png'
export { default as IconYourDeposited } from './resource/icon-your-deposited.png'

export { default as IconCheckOne } from './resource/check-one.png'
export { default as IconCoin } from './resource/icon-coin.png'
export { default as IconLanguage } from './resource/icon-language.png'
export { default as IconDiscord } from './resource/icon-discord.png'
export { default as IconGithub } from './resource/icon-github.png'
export { default as IconTele } from './resource/icon-tele.png'
export { default as IconTwitter } from './resource/icon-twitter.png'
export { default as IconWallet } from './resource/icon-wallet.png'
export { default as IconWithdraw } from './resource/icon-withdraw.png'
export { default as IconDeposit } from './resource/icon-deposit.png'