export { default as IconMetamaskWallet } from './resource/metasmask.png'
export { default as IconCoinbaseWallet } from './resource/coinbasewallet.png'
export { default as IconWalletConnect } from './resource/walletconnect.png'
export { default as IconPhantomWallet } from './resource/phantomwallet.png'
export { default as IconTrustWallet } from './resource/trustwallet.png'
export { default as IconArgentWallet } from './resource/argentwallet.png'
export { default as IconLedgerLive } from './resource/ledgerlive.png'

export { default as IconETH } from './resource/eth.png'
export { default as IconBTC } from './resource/btc.png'
export { default as IconUSDT } from './resource/usdt.png'
export { default as IconPudgy } from './resource/pudgy.png'
